#!/usr/bin/env python

import os
import io
import os.path
import argparse
import urllib

from eventdetector.annotate import process

parser = argparse.ArgumentParser(description='Annotate heel strike (HS) and foot off (FO) events.')
parser.add_argument('filename_in', metavar='filename_in', help="A c3d file with kinematics", type=str)
parser.add_argument('filename_out', metavar='filename_out', help="A c3d file to extract events to", type=str, default="out.c3d")
# parser.add_argument('--method', '-m',
#                     help="",
#                     type=str, choices=['neural','velocity','coordinate'],default="neural")

args = parser.parse_args()

process(args.filename_in, args.filename_out)
    
